### PR TITLE
Added 'Important Note' regarding 'Steam Game' section for first time use

### PR DESCRIPTION
**Pull request by bonaccolto90**
Forgot to add a little description on the Steam Game section for new users.

The note it's something that i had to do and wanted to share this information.

### CODE REVIEW

**Comment by solorvox** [comment]
The interaction with user from terminal is only if they do not install the script.  If user chooses to not install, only then does it require input.  (or times out)   

I did mention that in the error on script message, but I think the note text should more clearly state it's only if not installed.  And also that if not installed, the sudo for iptables will need to be run once per reboot.

**Comment by solorvox** [comment]
Oh, actually found that text in the readme under network access test.

" The prompt has a time-out of 15 seconds with a defaulting to no. In the event it was run from a GUI the user would not see the request for input on the terminal. This will then exit with an error. If your application appears to stop loading, please check it can run from the command line and verify the output. Adding the boot rule script will prevent this problem."

**Comment by bonaccolto90** [comment]
I installed the script, rebooted my pc (just to be safe), but the first interaction was needed anyways...

**Comment by bonaccolto90** [comment]
> Oh, actually found that text in the readme under network access test.
> 
> " The prompt has a time-out of 15 seconds with a defaulting to no. In the event it was run from a GUI the user would not see the request for input on the terminal. This will then exit with an error. If your application appears to stop loading, please check it can run from the command line and verify the output. Adding the boot rule script will prevent this problem."

I think this need to be quoted under the steam game paragraph, since the majority of users will use it for this.

**Comment by solorvox** [comment]
> I installed the script, rebooted my pc (just to be safe), but the first interaction was needed anyways...

Hum, sounds like a bug/issue then?  Would need some more info on what was happening.

**Comment by bonaccolto90** [comment]
> > I installed the script, rebooted my pc (just to be safe), but the first interaction was needed anyways...
> 
> Hum, sounds like a bug/issue then? Would need some more info on what was happening.

No, no... that what happened on the quote that you cited...

**Comment by solorvox** [comment]
> > Oh, actually found that text in the readme under network access test.
> > " The prompt has a time-out of 15 seconds with a defaulting to no. In the event it was run from a GUI the user would not see the request for input on the terminal. This will then exit with an error. If your application appears to stop loading, please check it can run from the command line and verify the output. Adding the boot rule script will prevent this problem."
> 
> I think this need to be quoted under the steam game paragraph, since the majority of users will use it for this.

This should only happen if you didn't run install and reboot.  I think maybe should add a note about rebooting so the system runs the NetworkManager scripts otherwise it won't right after installation without sudo + interaction.

**Comment by solorvox** [comment]
Alright, so if you'd like to change the pull request to add the note to the steam section of the readme.  Just to say users need to run install and reboot I'll be happy to merge.  Thanks

**Comment by bonaccolto90** [comment]
i removed the note on the steam section, updated the directory for the manual installation and added the reboot part at the end of the automatic and manual installation

**Comment by solorvox** [comment]
Hey, sorry for comment spam, but I just checked installer script.  It manually calls the nonet networkmanager script when installed.  So reboot not required, again, if it was installed.  Did you install the script first?

**Comment by bonaccolto90** [comment]
> Hey, sorry for comment spam, but I just checked installer script. It manually calls the nonet networkmanager script when installed. So reboot not required, again, if it was installed. Did you install the script first?

don't worry about the spam... yes, i installed it, just to be sure...

**Comment by bonaccolto90** [comment]
it can be an error on my side... i'm 80% sure of it...lemme check on my sister pc and report you back

**Comment by solorvox** [comment]
> don't worry about the spam... yes, i installed it, just to be sure...

Ok, then it sounds like a possible problem.  Would really love to know what went wrong.  The install.sh calls the NetworkManager script on line 69.  That should have then worked first run then without reboot.  

Any chance you'd be willing to help troubleshoot this and move it to an issue?  Likely require you to uninstall, reboot and install again to be sure.

**Comment by bonaccolto90** [comment]
ok, the new changes works! just need to logout and log back in... no reboot required...i'll change the readme right away!

**Comment by bonaccolto90** [comment]
Readme updated!

**Comment by solorvox** [comment]
I think we need clear up some confusion.  The reboot is required for the boot script to run automatically **if manually installed**.  The installer will run it for you during install so a reboot isn't required when installed.  

However, the logout is **required** for the new group to work in both cases.  The user's account can only use the new group after a logout.  If you can reword/clarify that in should be good.  Thanks

**Comment by bonaccolto90** [comment]
ok, so reboot if manual, logout if automatic...got it!

**Comment by bonaccolto90** [comment]
Fixed...sorry for the misunderstand!

**Pull request merged**
